### PR TITLE
issue-11  upgraded dependencies to add support for laravel 9.x

### PR DESCRIPTION
**Pull request by MedeirosDev**
Upgraded dependencies to add support for laravel 9.x

- [x] illuminate/database: ^9.0
- [x] orchestra/testbench: ^7.0

### CODE REVIEW

**Comment by abbasali** [comment]
Thanks for the PR @MedeirosDev. Can you please also update the tests matrix to include Laravel 9?

**Comment by MedeirosDev** [comment]
The tests for Laravel 9 are the same as for Laravel 8. I believe that it is not necessary to change the test suite

**Comment by abbasali** [comment]
You don't need to change the test suite. You just need to add Laravel 9.x to the [matrix](https://github.com/ranium/laravel-seedonce/blob/1.x/.github/workflows/tests.yml#L15) in the github workflow so that the tests are run against that version as well.

Thanks

**Comment by MedeirosDev** [comment]
> You don't need to change the test suite. You just need to add Laravel 9.x to the [matrix](https://github.com/ranium/laravel-seedonce/blob/1.x/.github/workflows/tests.yml#L15) in the github workflow so that the tests are run against that version as well.
> 
> Thanks

Gotcha, I'll update this

**Pull request merged**
